import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import { createStore } from "redux";
import { Provider } from "react-redux";
//import reducer from '.';
import { BrowserRouter as Router, Route,Link } from "react-router-dom";
//const store=createStore(reducer);
ReactDOM.render(<Router><App /></Router>, document.getElementById('root'));
registerServiceWorker();
